name: weather_app
description: "Weather app using flutter bloc."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.3.4 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  equatable: ^2.0.5
  path_provider: ^2.1.3
  flutter_bloc: ^8.1.5
  hydrated_bloc: ^9.1.5
  google_fonts: ^6.2.1
  weather_repository:
    path: packages/weather_repository

  cupertino_icons: ^1.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/