name: weather_repository
description: "Repository for weather api."
publish_to: none
version: 0.0.1
homepage:

environment:
  sdk: '>=3.3.4 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  api:
    path: ../api

dev_dependencies:
  flutter_lints: ^3.0.0